[features]
seeds = false
[programs.localnet]
tic_tac_toe = "RLjm256P3u3pnS8JNzd1Emp77eBctBbYw2MF9Aohzis"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/tunca/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
